server:
  port: 9191
spring:
  application:
    name: API-GateWay
  cloud:
    gateway:
      routes:
        - id: CHUYENBAY-SERVER
          uri: lb://CHUYENBAY-SERVER
          predicates:
            - Path=/chuyenbay/**
        - id: MAYBAY-SERVER
          uri: lb://MAYBAY-SERVER
          predicates:
            - Path=/maybay/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost